export {default as HomeIcon} from '../src/Assets/Icon/home.svg';
export {default as CategoriesIcon} from '../src/Assets/Icon/categories.svg';
export {default as AccountIcon} from '../src/Assets/Icon/account.svg';
export {default as ReferalIcon} from '../src/Assets/Icon/referal.svg';
export {default as CartIcon} from '../src/Assets/Icon/cart.svg';
export {default as LocationIcon} from '../src/Assets/Icon/location.svg';
export {default as DownarrIcon} from '../src/Assets/Icon/downarr.svg';
export { default as Downarrow } from '../src/Assets/Icon/downarrow.svg';
export {default as ProfileIcon} from '../src/Assets/Icon/profile.svg';
export {default as SearchIcon} from '../src/Assets/Icon/search.svg';
export {default as PlusIcon} from '../src/Assets/Icon/plus.svg';
export {default as RightarrowIcon} from '../src/Assets/Icon/rightarr.svg';
export {default as DiscountIcon} from '../src/Assets/Icon/discount.svg';
export {default as BackIcon} from '../src/Assets/Icon/back.svg';
export {default as EditIcon} from '../src/Assets/Icon/edit.svg';
export {default as CrossIcon} from '../src/Assets/Icon/cross.svg';
export {default as Cross2Icon} from '../src/Assets/Icon/cross2.svg';
export {default as WorkIcon} from '../src/Assets/Icon/work.svg';
export {default as HistoryIcon} from '../src/Assets/Icon/history.svg';
export {default as ProductsIcon} from '../src/Assets/Icon/product.svg';
export {default as UploadIcon} from '../src/Assets/Icon/upload.svg';
export {default as DeleteIcon} from '../src/Assets/Icon/delete.svg';
export { default as ThreedotIcon } from '../src/Assets/Icon/threedot.svg';
export { default as ViewIcon } from '../src/Assets/Icon/view.svg';
export { default as StatusIcon } from '../src/Assets/Icon/status.svg';
export {default as CheckboxIcon} from '../src/Assets/Icon/checkbox.svg';
export {default as CheckboxactiveIcon} from '../src/Assets/Icon/checkboxactive.svg';
export {default as SignoutIcon} from '../src/Assets/Icon/signout.svg';
export {default as OrderIcon} from '../src/Assets/Icon/order.svg';
export { default as SortIcon } from '../src/Assets/Icon/sort.svg';
export { default as StarIcon } from '../src/Assets/Icon/star.svg';
export { default as DeliveryIcon } from '../src/Assets/Icon/delivery.svg';
export { default as NotificationIcon } from '../src/Assets/Icon/notification.svg';
export { default as ChatIcon } from '../src/Assets/Icon/chat.svg';
export { default as RadioonIcon } from '../src/Assets/Icon/radioon.svg';
export { default as RadiooffIcon } from '../src/Assets/Icon/radiooff.svg';
export { default as Plus2Icon } from '../src/Assets/Icon/plus2.svg';
export { default as MinusIcon } from '../src/Assets/Icon/minus.svg';
export { default as CameraIcon } from '../src/Assets/Icon/camera.svg';
export { default as ImageIcon } from '../src/Assets/Icon/image.svg';